/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author هزيم الرعد
 */
public class MainFrame extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private JPanel mainPanel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("TaskFlow - Personal Project Manager");
        setSize(850, 550); 
        setLocationRelativeTo(null); 
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
        this.setContentPane(mainPanel);
        switchPage("Login");
       // تعريف اللوحات (الصفحات) داخل المحرك
        mainPanel.add(new LoginPanel(this), "Login");
        mainPanel.add(new DashboardPanel(this), "Dashboard"); 
        mainPanel.add(new SettingsPanel(this), "Settings");
        mainPanel.add(new ManageTasksPanel(this), "ManageTasks");
        this.setContentPane(mainPanel);
        switchPage("Login");
    }
    public void switchPage(String pageName) {
        cardLayout.show(mainPanel, pageName);
        if (pageName.equals("Login")) {
            this.setSize(400, 300); 
        } else {
            this.setSize(850, 550); 
        }
        this.setLocationRelativeTo(null); 
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // هذا السطر يجبر الجافا على استخدام شكل ثيم الويندوز الأصلي لجهازك
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

